#!/bin/bash

# make links first
command_exists () {
  type "$1" &> /dev/null ;
}

if ! command_exists git; then
  echo "please install git first :-("
  exit
fi

for dotfile in `ls -a | grep "^\.[a-z]" | cut -d\/ -f1 | grep -v "^\.git$" | grep -v "^\.gitignore$"`;
do
  ln -s -i $PWD/$dotfile ~
done

cd zsh && ./setup
cd ..

echo "install vim plugins"
vim +PlugInstall +qall

if [ ! -f ~/.profile ]; then
  echo "source ~/.bashrc" >>~/.profile
fi

echo "source profile"
. ~/.profile
