#!/usr/bin/env python
import pip


def main():
    for dist in pip.get_installed_distributions(local_only=True):
        print 'Upgrade', dist.key
        pip.main(['install', '--upgrade', dist.key])
        print 'Done\n'


if __name__ == '__main__':
    main()
