#!/usr/bin/python
# coding: utf-8
import sys
import time
import datetime

FORMATS = ['%Y-%m-%d', '%Y-%m-%d %H', '%Y-%m-%d %H:%M', '%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S,%f']


def fromtimestamp(t):
    return str(datetime.datetime.fromtimestamp(t))


def totimestamp(s):
    for fmt in FORMATS:
        try:
            return time.mktime(time.strptime(s, fmt))
        except:
            pass
    raise Exception('bad format')


def main():
    if not len(sys.argv) == 2:
        print int(time.time())
        return
    ts = None
    dt = None
    try:
        ts = float(sys.argv[1])
        dt = fromtimestamp(ts)
    except:
        try:
            ts = totimestamp(sys.argv[1])
            dt = fromtimestamp(ts)
        except:
            pass
    if dt and ts:
        print dt, ts
    else:
        print 'bad time format or value'


if __name__ == '__main__':
    main()
