#!/usr/bin/python
# coding: utf-8
import sys
import time
import datetime

FORMATS = ['%Y-%m-%d', '%Y-%m-%d %H', '%Y-%m-%d %H:%M', '%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S,%f']


def fromtimestamp(t):
    return str(datetime.datetime.fromtimestamp(t))


def totimestamp(s):
    for fmt in FORMATS:
        try:
            return time.mktime(time.strptime(s, fmt))
        except:
            pass
    return -1


def main():
    if not len(sys.argv) == 3:
        print 'Usage: %s [-todate|-totime] value' % sys.argv[0]
        return
    elif sys.argv[1] == '-todate':
        print fromtimestamp(float(sys.argv[2]))
    elif sys.argv[1] == '-totime':
        t = totimestamp(sys.argv[2])
        print t if t >= 0 else 'invalid format "%s"' % sys.argv[2]
    else:
        print 'invalid argument "%s"' % sys.argv[1]


if __name__ == '__main__':
    main()
